name: 'Github Action'
on:
  push:
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Install dependencies
        run: npm ci

      - name: Build
        run: npm run package

      - name: Commit build
        uses: stefanzweifel/git-auto-commit-action@v4.1.6
        with:
          file_pattern: dist/index.js
          commit_message: Update build
          branch: ${{ github.head_ref }}

      - name: Unit tests
        run: npm test

      - name: E2E test
        uses: ./
        with:
          url: https://raw.githubusercontent.com/olivr-com/download-file-action/master/LICENSE
